syntax = "proto3";

package race.v1;

option csharp_namespace = "HA3.Proto.Race.V1";

message Vector3 {
  double x = 1;
  double y = 2;
  double z = 3;
}

message Quaternion {
  double x = 1;
  double y = 2;
  double z = 3;
  double w = 4;
}

message WheelAngles {
  double front_left_rad = 1;
  double front_right_rad = 2;
}

message WheelSpeeds {
  double front_left_rps = 1;
  double front_right_rps = 2;
  double rear_left_rps = 3;
  double rear_right_rps = 4;
}

message GetCarStateResponse {
  uint64 car_id = 1;
  Vector3 position = 2;
  Quaternion orientation = 3;
  double speed_mps = 4;
  double engine_rpm = 5;
  int32 gear = 6;
  double throttle_applied = 7;
  double brake_applied = 8;
  WheelAngles wheel_steering = 9;
  WheelSpeeds wheel_speeds = 10;

  reserved 11 to 19;
}
