syntax = "proto3";

package race.v1;

option csharp_namespace = "HA3.Proto.Race.V1";

message Track {
    string id = 1;
    string hash = 2;
    double lap_length = 3;
    repeated TrackPoint centerline = 4;
    repeated TrackEdgePoint left_edge = 5;
    repeated TrackEdgePoint right_edge = 6;
}

message TrackPoint {
    double x = 1;
    double y = 2;
    double z = 3;
    double s = 4;
    double theta = 5;
    double kappa = 6;
}

message TrackEdgePoint {
    double x = 1;
    double y = 2;
    double z = 3;
}

service TrackService {
    rpc GetTrack (GetTrackRequest) returns (Track);
}

message GetTrackRequest {
    string track_id = 1;
}
