name: Release Proto Packages

on:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'

  build-csharp:
    permissions:
      contents: read
      packages: write
    needs: lint
    uses: ./.github/workflows/build-csharp.yaml
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit # Ważne: przekazuje GITHUB_TOKEN do sub-workflow

  build-typescript:
    permissions:
      contents: read
      packages: write
    needs: lint
    uses: ./.github/workflows/build-typescript.yaml
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit